
language: generic
dist: bionic
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

before_install:
   - wget -c https://files.seeedstudio.com/arduino/seeed-arduino-ci.sh

script:
   - chmod +x seeed-arduino-ci.sh
   - cat $PWD/seeed-arduino-ci.sh
   - bash $PWD/seeed-arduino-ci.sh Fingerprint_lock:uno/jumper:uno Seeed-Studio/Seeed_Arduino_SFUD Seeed-Studio/Seeed_Arduino_FS adafruit/Adafruit_ZeroTimer Seeed-Studio/Seeed_Arduino_KCT202 arduino-libraries/Servo Seeed-Studio/Grove_LCD_RGB_Backlight adafruit/Adafruit_NeoPixel

notifications:
  email:
    on_success: change
    on_failure: change
